name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-west-2
  DOCKER_IMAGE: clovin-security
  DATABASE_URL: mysql://admin:${{ secrets.DB_PASSWORD }}@clovin-security-db.c56ay4eawb7p.us-west-2.rds.amazonaws.com:3306/vulnerabilities

jobs:
  docker:
    name: 'Docker'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_REPO }}:latest
        build-args: |
          DATABASE_URL=mysql://admin:${{ secrets.DB_PASSWORD }}@clovin-security-db.c56ay4eawb7p.us-west-2.rds.amazonaws.com:3306/vulnerabilities

  terraform:
    name: 'Terraform'
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Generate SSH Key
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""

    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Plan
      run: |
        terraform plan \
          -var="db_password=${{ secrets.DB_PASSWORD }}" \
          -var="public_key_path=~/.ssh/id_rsa.pub" \
          -var="docker_username=${{ secrets.DOCKER_HUB_USERNAME }}"
      
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="db_password=${{ secrets.DB_PASSWORD }}" \
          -var="public_key_path=~/.ssh/id_rsa.pub" \
          -var="docker_username=${{ secrets.DOCKER_HUB_USERNAME }}"
